experiment: 'template'
level: 'debug'

dataset:
  train_csv: ~
  val_csv: ~
  test_csv: ~
  feature_dir: ~
  num_workers: 4
  drop_last: False

model:
  vocab_dim: 512
  text:
    proj_act: relu
  visual:
    max_len: 18
    dropout: 0.4
    transformer:
      layer: 6
      width: 128
      heads: 16

train:
  batch_size: 128
  gradient_accumulation_steps: 1
  log_step: 100
  lr: 0.0001
  lr_decay: ~
  epoch: 10
  save_freq: 1

seed:
  default_seed: 1

val:
  batch_size: 100    
  step: 2
  early_stopping: True
  metrics: 'R1'
  higher_better: True


